apiVersion: apps/v1
kind: Deployment
metadata:
  name: markdown-manager
  labels:
    app: markdown-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: markdown-manager
  template:
    metadata:
      labels:
        app: markdown-manager
    spec:
      containers:
      - name: markdown-manager
        image: jeremy-schaab/markdown-manager:latest
        ports:
        - containerPort: 8501
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: STREAMLIT_HOST
          value: "0.0.0.0"
        - name: STREAMLIT_PORT
          value: "8501"
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: openai-endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: openai-api-key
        - name: AZURE_OPENAI_CHAT_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: openai-deployment
        - name: AZURE_STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: storage-connection-string
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: sessions
          mountPath: /app/sessions
      volumes:
      - name: logs
        emptyDir: {}
      - name: sessions
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: markdown-manager-service
spec:
  selector:
    app: markdown-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  openai-deployment: "gpt-4"
  openai-api-version: "2024-02-15-preview"
  max-tokens: "128000"
  temperature: "0.25"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
stringData:
  openai-endpoint: "https://your-resource.openai.azure.com/"
  openai-api-key: "your-api-key-here"
  storage-connection-string: "your-storage-connection-string"